 module tcljx.compiler {
   requires transitive tcljc.core;

   // exports tcljx.alpha.ptest__align;
   // exports tcljx.alpha.ptest;
   // exports tcljx.alpha.ptest__impl;
   exports tcljx.alpha.ptest__style;
   exports tcljx.alpha.textflow__ansi;
   exports tcljx.alpha.textflow;
   exports tcljx.alpha.textflow__insn;
   exports tcljx.alpha.textflow__pp;
   exports tcljx.classgen.build;
   // exports tcljx.classgen.classdata;
   exports tcljx.classgen.classfile;
   exports tcljx.classgen.codegen;
   exports tcljx.classgen.condgen;
   exports tcljx.classgen.constgen;
   exports tcljx.classgen.defgen;
   exports tcljx.classgen.emit;
   exports tcljx.classgen.entity;
   exports tcljx.classgen.fnenv;
   exports tcljx.classgen.fngen;
   exports tcljx.classgen.insn;
   exports tcljx.classgen.macro;
   exports tcljx.classgen.primitive;
   exports tcljx.classgen.publics;
   exports tcljx.classgen.runtime;
   exports tcljx.classgen.segment;
   exports tcljx.classgen.switchgen;
   exports tcljx.classgen.trygen;
   exports tcljx.classgen.typegen;
   exports tcljx.classgen.universe;
   exports tcljx.classgen.util;
   exports tcljx.data.code;
   exports tcljx.data.config;
   exports tcljx.data.context;
   exports tcljx.data.files;
   exports tcljx.data.ir;
   exports tcljx.data.member;
   exports tcljx.data.meta;
   exports tcljx.data.reflect;
   exports tcljx.data.resolve;
   exports tcljx.data.type;
   exports tcljx.data.wrong;
   exports tcljx.main;
   exports tcljx.main.efmt;
   exports tcljx.main.invoke;
   exports tcljx.main.options;
   exports tcljx.main.tclj0;
   exports tcljx.main.tclj1;
   exports tcljx.main.watcher;
   exports tcljx.parser.constant;
   exports tcljx.parser.def;
   exports tcljx.parser.deftype;
   exports tcljx.parser.fn;
   exports tcljx.parser.form;
   exports tcljx.parser.interop;
   exports tcljx.parser.let;
   exports tcljx.parser.loop;
   exports tcljx.parser.namespace;
   exports tcljx.parser.newobj;
   exports tcljx.parser.parse;
   exports tcljx.parser.reader;
   exports tcljx.parser.syntax;
   exports tcljx.parser.trycatch;
}
